clone_folder: c:\projects\azure-rest-api-specs

environment:
  opbuilduser: "OpenPublishBuild"
  opbuilduseremail: "vscopbld@microsoft.com"
  access_token:
    secure: JWSy9tPo2eoTYpPQplvokf4IiVk6onNBbWwAs6nNWWyQ2JaO+MRAg/QzbJnTjpUm

install:
  - git checkout master

before_build:
  - ps: |
        if($env:APPVEYOR_SCHEDULED_BUILD -or ($env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL -ne $env:opbuilduseremail))
        {
          $env:IS_CI_BUILD_ENABLED=$true
          echo "CI build is enabled"
        }
        if($env:IS_CI_BUILD_ENABLED)
        {
          git config --global credential.helper store
          Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
          git config --global user.email $env:opbuilduseremail
          git config --global user.name $env:opbuilduser
          scripts\UpdateSrcRepo.ps1
        }
        
build_script:
  - ps: |
        if($env:IS_CI_BUILD_ENABLED)
        {
          scripts\build.ps1
        }

on_success:
  - |
    if "%IS_CI_BUILD_ENABLED%" == "True" (
      git add .
      git diff --quiet --exit-code --cached || git commit -m "Rest document Updated by CI" && git push -u origin master
      appveyor AddMessage "Rest document Updated"
    )
